version: 0.2
env:
  variables:
    APP_NAME: "codename-creator"
    PACKAGE: "github.com/bense4ger/codename-creator" 
phases:
  install: 
    commands:
      - echo ${GOPATH}
      - echo Create dir in GOPATH for sources
      - mkdir -p ${GOPATH}/src/${PACKAGE}

      - echo Copy source files into GOPATH
      - cp -a ${CODEBUILD_SRC_DIR}/.  ${GOPATH}/src/${PACKAGE}

      - cd ${GOPATH}/src/${PACKAGE} && go get ./...
  build:
    commands:
      - cd ${GOPATH}/src/${PACKAGE} && go build -o ${CODEBUILD_SRC_DIR}/${APP_NAME}
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file serverless.yml --s3-bucket codepipeline-us-east-1-904718901445
artifacts:
  files:
    - serverless.yml