version: 0.2
env:
  variables:
    PACKAGE: "github.com/bense4ger/codename-creator"
phases:
  install:
    commands:
      - mkdir -p ${GOPATH}/src/github.com/bense4ger/codename-creator
      - cp -a ${CODEBUILD_SRC_DIR}/. ${GOPATH}/src/github.com/bense4ger/codename-creator
      - cd ${GOPATH}/src/github.com/bense4ger/codename-creator && ls -a
      - cd ${GOPATH}/src/github.com/bense4ger/codename-creator && go get ./...
  build:
    commands:
      - cd ${GOPATH}/src/github.com/bense4ger/codename-creator && go build -o ${CODEBUILD_SRC_DIR}/codename-creator
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file serverless.yml --s3-bucket codepipeline-us-east-1-904718901445
artifacts:
  files:
    - serverless.yml