version: 0.2

phases:
  install:
    commands:
      - go get github.com/aws/aws-lambda-go/lambda
  build:
    commands:
      - go build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - codename-creator