version: 0.2
env:
  variables:
    PACKAGE: "github.com/bense4ger/codename-creator"
phases:
  install:
    commands:
      - export GOPATH="${CODEBUILD_SRC_DIR}/${WORKDIR}"; echo ${GOPATH}; mkdir -p "${GOPATH}/bin"; mkdir -p "${GOPATH}${PACKAGE}"
      - export GOPATH="${CODEBUILD_SRC_DIR}/${WORKDIR}"; export PATH="${PATH}:/usr/local/go/bin:${GOPATH}/bin"
      - export GOPATH="${CODEBUILD_SRC_DIR}/${WORKDIR}"; cp -a ${CODEBUILD_SRC_DIR}/. ${GOPATH}${PACKAGE}
      - export GOPATH="${CODEBUILD_SRC_DIR}/${WORKDIR}"; cd ${GOPATH}; ls -a
      - export GOPATH="${CODEBUILD_SRC_DIR}/${WORKDIR}"; cd ${GOPATH}${PACKAGE}; go get ./...
  build:
    commands:
      - cd ${GOPATH}/src/${PACKAGE}; go build -o ${CODEBUILD_SRC_DIR}/codename-creator
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file serverless.yml --s3-bucket codepipeline-us-east-1-904718901445
artifacts:
  files:
    - serverless.yml