version: 0.2

phases:
  install:
    commands:
      - go get github.com/aws/aws-lambda-go/lambda
  build:
    commands:
      - go build -o codename-creator
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file serverless.yml --s3-bucket bense4ger-deploy
artifacts:
  type: zip
  files:
    - serverless.yml