version: 0.2

phases:
  install:
    commands:
      - go get github.com/aws/aws-lambda-go/lambda
  build:
    commands:
      - go build -o codename-creator
      - zip codename-creator.zip codename-creator
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file serverless.yml --s3-bucket $BUILD_OUTPUT_BUCKET
artifacts:
  files:
    - serverless.yml