AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  CodenameCreatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: codename-creator
      Runtime: go1.x
      CodeUri: ./
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        CodenameCreatorApi:
          Type: Api
          Properties:
            Path: /
            Method: GET

  CodenameTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CodenameData
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: ident
          AttributeType: N
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: ident
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
