AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CodenameCreatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: codename-generator
      Runtime: go1.x
      CodeUri: ./codename-creator
      Events:
        CodenameCreatorApi:
          Type: Api
          Properties:
            Path: /
            Method: GET